// Vue3/src/App.vue
<template>
  <button @click="disconnectWallet" v-if="accountAddress">Disconnect</button>
  <button @click="connectWallet" v-else>Connect to Pera Wallet</button>

  <div v-if="accountAddress">Connected to {{ accountAddress }}</div>
</template>

<script>
import { PeraWalletConnect } from "@perawallet/connect";

const peraWallet = new PeraWalletConnect();

export default {
  name: "App",
  data() {
    return {
      accountAddress: "",
    };
  },
  mounted() {
    peraWallet
      .reconnectSession()
      .then((accounts) => {
        peraWallet.connector.on("disconnect", this.disconnectWallet);

        if (accounts.length) {
          this.accountAddress = accounts[0];
        }
      })
      .catch((error) => {
        if (error?.data?.type !== "CONNECT_MODAL_CLOSED") {
          console.log(error);
        }
      });
  },
  methods: {
    connectWallet() {
      peraWallet
        .connect()
        .then((accounts) => {
          peraWallet.connector.on("disconnect", this.disconnectWallet);

          this.accountAddress = accounts[0];
        })
        .catch((e) => console.log(e));
    },
    disconnectWallet() {
      peraWallet.disconnect().then(() => (this.accountAddress = null));
    },
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// React/src/App.js
import { useState, useEffect } from "react";
import { PeraWalletConnect } from "@perawallet/connect";

import "./styles.css";

const peraWallet = new PeraWalletConnect();

export default function App() {
  const [accountAddress, setAccountAddress] = useState(null);
  const isConnectedToPeraWallet = !!accountAddress;

  useEffect(() => {
    // Reconnect to the session when the component is mounted
    peraWallet
      .reconnectSession()
      .then((accounts) => {
        peraWallet.connector.on("disconnect", handleDisconnectWalletClick);

        if (accounts.length) {
          setAccountAddress(accounts[0]);
        }
      })
      .catch((e) => console.log(e));
  }, []);

  return (
    <button
      onClick={
        isConnectedToPeraWallet
          ? handleDisconnectWalletClick
          : handleConnectWalletClick
      }
    >
      {isConnectedToPeraWallet ? "Disconnect" : "Connect to Pera Wallet"}
    </button>
  );

  function handleConnectWalletClick() {
    peraWallet
      .connect()
      .then((newAccounts) => {
        peraWallet.connector.on("disconnect", handleDisconnectWalletClick);

        setAccountAddress(newAccounts[0]);
      })
      .catch((error) => {
        if (error?.data?.type !== "CONNECT_MODAL_CLOSED") {
          console.log(error);
        }
      });
  }

  function handleDisconnectWalletClick() {
    peraWallet.disconnect();

    setAccountAddress(null);
  }
}
